### ISSUE TITLE
MiSTer FDS not loading correctly

### ISSUE THREAD

**Issue by ll432** [wizzomafizzo/tapto#28]
When loading Nintendo FamiCom Disk System Games with .fds extension in the /games/NES directory, MiSTer loads "FDS" core with a gray screen. In that core's menu, It shows FDS on the side and when you attempt to load a rom, it gives an empty dir error. Core settings are different from settings saved for NES core. I have not seen this core before?

I created a new directory /games/FDS copied the FDS BIOS and the file being loaded via NFC to that dir. The NFC is still pointing to the rom in the /games/NES folder... This seemed to allow the core and rom to load correctly.  It still says "FDS" on the side and when attempting to load a rom from the menu, only the files copied to the /games/FDS dir show, but it behaves as expected (other than the FDS vs NES dir).

I have tested this with Gyruss and Kiki Kaikai. I have not checked any games that allow saves (IE: Metroid or Zelda). 

I have ACR122U Reader. Using the taptui script to write to NFC. 215 NFC Card.

**Comment by wizzomafizzo** [comment]
Thanks for reporting. I'll try take a look at this soon. I have gotten quite a few reports now that these core which support multiple systems are having trouble launching

**Comment by wizzomafizzo** [comment]
When a game is detected as FDS, it loads the NES core with the "setname" FDS which means the NES core will use a folder called FDS instead of NES everywhere. So it's sort of like a different core

Because of this, it attempts to automatically load the FDS BIOS file "/media/fat/games/FDS/boot0.rom" which only exists in the NES folder and so it fails to launch

I will add a workaround to point to the correct BIOS location. But for now you can also create a folder on your SD card's game folder called "FDS" and copy the file "boot0.rom" from the NES folder into the new FDS folder. Then they should start working again

**Comment by ll432** [comment]
When I saw the setname "FDS" I took a shot in the dark and created a /games/FDS folder. Tho I also needed to copy at least one file with .fds extension along with the BIOS. Otherwise, when you attempt to open another ROM, you get an error screen. If you never manually open ROMs after loading an FDS game via NFC, you would never notice this. 

Thank you for looking into this!!

**Comment by ll432** [comment]
Honestly, As it is now, is awesome! At first I thought it was gonna be gimmicky, but it ended up bring back a level nostalgia I didn't expect.

Thank You for this!!
